# Generated by Django 4.2 on 2023-11-11 12:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.document_file_patch),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='default profile', max_length=20, null=True, unique=True),
        ),
    ]
