# Generated by Django 4.2 on 2023-11-12 19:29

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.document_file_patch, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(upload_to=core.models.event_file_patch, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
